TIMEOUT=30000;


ADV_SEARCH_HEIGHT_SMALL='small';
ADV_SEARCH_HEIGHT_MEDIUM='medium';
ADV_SEARCH_HEIGHT_HEIGHT='height';
ADV_SEARCH_WEIGHT_SMALL='small';
ADV_SEARCH_WEIGHT_MEDIUM='medium';
ADV_SEARCH_WEIGHT_HEIGHT='height';
SORT_NUMERICALLY_ASCENDING='Lowest Number (First)';
SORT_NUMERICALLY_DESCENDING='Highest Number (First)';
SORT_ALPHABETICALLY_ASCENDING='A-Z';
SORT_ALPHABETICALLY_DESCENDING='Z-A';


